apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/data/metrics'
        prometheus.io/port: '80'
    spec:
            #      schedulerName: customScheduler
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
